server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/state_db
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

webclient:
  district-service-url: http://localhost:8082
