server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/district_db
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
